version: '3'

services:
  postgres:
    image: postgres:10-alpine
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    user: www-data
    working_dir: ${APP_DIR}
    volumes:
      - ${PWD}:${APP_DIR}

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${PWD}:${APP_DIR}

  redis:
    image: redis:4-alpine

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    env_file:
      - .env
    user: node
    working_dir: ${APP_DIR}
    volumes:
      - ${PWD}:${APP_DIR}
    command: sh -c "yarn && yarn dev"
